"""empty message

Revision ID: 11874cdb5276
Revises: 
Create Date: 2021-02-20 03:41:26.455700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11874cdb5276'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('luogu_user', schema=None) as batch_op:
        batch_op.drop_column('is_auth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('luogu_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_auth', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
