"""deletewant

Revision ID: 250ef2ca606e
Revises: d2eddc1793cf
Create Date: 2021-02-23 02:19:36.316402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250ef2ca606e'
down_revision = 'd2eddc1793cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delete_want', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('approved_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('submit_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delete_want', schema=None) as batch_op:
        batch_op.drop_column('submit_time')
        batch_op.drop_column('approved_time')
        batch_op.drop_column('approved_message')

    # ### end Alembic commands ###
