"""length

Revision ID: 3b9d5f8e5cd1
Revises: 
Create Date: 2020-06-07 18:10:36.455678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9d5f8e5cd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ben_ben_text', table_name='ben_ben')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ben_ben_text', 'ben_ben', ['text'], unique=False)
    # ### end Alembic commands ###
