"""deletewant-user

Revision ID: ae76d24072a7
Revises: 250ef2ca606e
Create Date: 2021-02-24 06:02:30.134596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae76d24072a7'
down_revision = '250ef2ca606e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delete_want', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submit_user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delete_want', schema=None) as batch_op:
        batch_op.drop_column('submit_user_id')

    # ### end Alembic commands ###
