"""delete_want's reason

Revision ID: d2eddc1793cf
Revises: 11874cdb5276
Create Date: 2021-02-20 07:31:18.405292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2eddc1793cf'
down_revision = '11874cdb5276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delete_want', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delete_want', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
